# Generated by Django 4.1.7 on 2023-05-17 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_engine_atb',
            name='search_date',
            field=models.DateTimeField(default=datetime.date(2023, 5, 17)),
        ),
        migrations.AlterField(
            model_name='search_engine_glove',
            name='search_date',
            field=models.DateTimeField(default=datetime.date(2023, 5, 17)),
        ),
        migrations.AlterField(
            model_name='search_engine_silpo',
            name='search_date',
            field=models.DateTimeField(default=datetime.date(2023, 5, 17)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='quantity',
            field=models.CharField(max_length=255),
        ),
    ]
