# Generated by Django 4.1.7 on 2023-03-20 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search_engine_glove',
            name='product_volume',
        ),
        migrations.RemoveField(
            model_name='search_engine_silpo',
            name='product_volume',
        ),
    ]
