# Generated by Django 4.1.7 on 2023-05-17 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_search_engine_atb_search_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_engine_atb',
            name='search_date',
            field=models.DateTimeField(default=datetime.date(2023, 5, 18)),
        ),
        migrations.AlterField(
            model_name='search_engine_glove',
            name='search_date',
            field=models.DateTimeField(default=datetime.date(2023, 5, 18)),
        ),
        migrations.AlterField(
            model_name='search_engine_silpo',
            name='search_date',
            field=models.DateTimeField(default=datetime.date(2023, 5, 18)),
        ),
    ]
