# Generated by Django 4.1.7 on 2023-03-13 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_search_engine_atb_product_volume_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='search_engine_metro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_request', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.CharField(max_length=200)),
                ('product_volume', models.CharField(max_length=200)),
                ('search_date', models.DateTimeField(default=datetime.datetime(2023, 3, 13, 22, 15, 53, 381243))),
                ('product_image', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['-search_date'],
            },
        ),
        migrations.DeleteModel(
            name='search_engine_arsen',
        ),
        migrations.AlterField(
            model_name='search_engine_atb',
            name='search_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 13, 22, 15, 53, 381243)),
        ),
        migrations.AlterField(
            model_name='search_engine_silpo',
            name='search_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 13, 22, 15, 53, 380137)),
        ),
    ]
